### ISSUE TITLE
As a user, I can filter food trucks/parks based on ratings that go by .5 intervals.

### ISSUE THREAD

**Issue by clairebingham** [colin19/Parkd#52]
-More of a nice to have, it would be nice to filter based on .5 intervals instead of the current 1 intervals since some ratings are so close.

**Comment by GuanSuns** [comment]
In fact, we have already supported filter based on 0.2 intervals. Since most of the ratings are in the range of 4.0 to 4.8, we have a smaller interval 0.2 for ratings from 4.0 to 4.8. Also, since only a few trucks/parks have a rating of 1.0 to 4.0, we decided to use a larger interval 1 in that range.

**Comment by GuanSuns** [comment]
After discussing this issue, we decide to reorder the options to make the smaller intervals more noticeable.
